### ISSUE TITLE
Error using #to_activerecord_hash

### ISSUE THREAD

**Issue by rderoldan1** [beauby/jsonapi_parser#9]
I get this error while using this _to_activerecord_hash_ (related to #7 )

```bash
NoMethodError: undefined method `[]' for nil:NilClass
	from /var/lib/gems/2.2.0/gems/jsonapi_parser-0.5.5/lib/json/api/resource/active_record.rb:142:in `filter_keys'
	from /var/lib/gems/2.2.0/gems/jsonapi_parser-0.5.5/lib/json/api/resource/active_record.rb:82:in `attributes_for_activerecord_hash'
	from /var/lib/gems/2.2.0/gems/jsonapi_parser-0.5.5/lib/json/api/resource/active_record.rb:72:in `to_activerecord_hash'
```

The related object is 
```ruby
#<JSON::API::Resource:0x00000006905528
 @attributes=
  #<JSON::API::Attributes:0x00000006905398
   @attributes=
    {"name"=>nil,
     "tax_id"=>"19818",
     "description"=>nil,
     "image_url"=>nil,
     "preferred_name"=>"PALMER SECOND BAPTIST CHURCH",
     "created_at"=>"2016-03-28T18:41:34.000Z",
     "updated_at"=>"2016-03-28T18:41:34.000Z",
     "json_data"=>{"deductibility"=>1, "sort_name"=>3514},
     "type_of_cause"=>nil,
     "images"=>[],
     "primary_image"=>nil}>,
 @attributes_hash=
  {"name"=>nil,
   "tax_id"=>"19818",
   "description"=>nil,
   "image_url"=>nil,
   "preferred_name"=>"PALMER SECOND BAPTIST CHURCH",
   "created_at"=>"2016-03-28T18:41:34.000Z",
   "updated_at"=>"2016-03-28T18:41:34.000Z",
   "json_data"=>{"deductibility"=>1, "sort_name"=>3514},
   "type_of_cause"=>nil,
   "images"=>[],
   "primary_image"=>nil},
 @id="472",
 @id_optional=true,
 @links=#<JSON::API::Links:0x000000068c3f88 @links={}>,
 @links_hash={},
 @options={},
 @relationships=#<JSON::API::Relationships:0x000000069040d8 @relationships={}>,
 @relationships_hash={},
 @type="causes">
```

**Comment by rderoldan1** [comment]
It works if I call it like this : 
```ruby
   document.data.to_activerecord_hash({ attributes: { }, relationships: { } })
```

**Comment by beauby** [comment]
Hi @rderoldan1 – You are right. #10 should fix your issue.
